#!/usr/bin/env node

var path = require('path');
var fs = require('fs-extra');
var webpack = require('webpack');
var webpackConfig = require(path.join(process.cwd(), 'webpack.config'));

fs.emptyDirSync(path.join(process.cwd(), 'dist'));

fs.copySync(path.join(process.cwd(), 'src'), path.join(process.cwd(), 'dist'));

webpack(webpackConfig)
  .run(function(err, stats) {
      // ...
    });
